/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package xyz.galinfo.galipos.panels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import xyz.galinfo.galipos.models.CmbItem;
import xyz.galinfo.galipos.models.ItemTransaksi;
import xyz.galinfo.galipos.models.Produk;
import xyz.galinfo.galipos.models.User;

/**
 *
 * @author janud
 */
public class PanelPenjualan extends javax.swing.JPanel {

  /**
   * Creates new form PanelDashboard
   */
  public PanelPenjualan() {
    initComponents();
    txtPenjualanKodeProduk.requestFocus();
    ArrayList<CmbItem> cmbItems = new ArrayList<>();
    ArrayList<User> users = User.getActiveBuyers();
    cmbItems.add(new CmbItem("1", "Umum"));
    cmbPenjualanBuyer.removeAllItems();
    for (CmbItem item : cmbItems) {
      cmbPenjualanBuyer.addItem(item);
    }
    for (User user : users) {
      cmbPenjualanBuyer.addItem(new CmbItem(user.getId() + "", user.getNama()));
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    cmbPenjualanBuyer = new javax.swing.JComboBox<>();
    jLabel9 = new javax.swing.JLabel();
    txtPenjualanBuyerNama = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    txtPenjualanKodeProduk = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jButton4 = new javax.swing.JButton();

    jPanel1.setBackground(new java.awt.Color(0, 102, 153));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("PENJUALAN");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setText("Jumlah");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

    jTextField1.setEnabled(false);
    jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, -1));

    jLabel3.setText("Diskon");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

    jTextField2.setEnabled(false);
    jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 240, -1));

    jLabel4.setText("Total");
    jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

    jTextField3.setEnabled(false);
    jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, -1));

    jLabel5.setText("Dibayar");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
    jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, -1));

    jLabel6.setText("Kembali");
    jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

    jTextField5.setEnabled(false);
    jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, -1));

    jButton2.setText("Batal");
    jButton2.setEnabled(false);
    jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

    jButton3.setText("Simpan");
    jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

    jLabel8.setText("Buyer");
    jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    cmbPenjualanBuyer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbPenjualanBuyerActionPerformed(evt);
      }
    });
    jPanel2.add(cmbPenjualanBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

    jLabel9.setText("Nama");
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
    jPanel2.add(txtPenjualanBuyerNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, -1));

    jLabel7.setText("Kode produk");

    txtPenjualanKodeProduk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPenjualanKodeProdukActionPerformed(evt);
      }
    });

    jButton1.setText("Tambahkan");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPenjualanKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(txtPenjualanKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton1))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Kode", "Nama", "Harga", "Jumlah", "Total"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, true, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jTable1KeyPressed(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton4.setText("Hapus item");
    jButton4.setEnabled(false);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4)
            .addGap(0, 0, Short.MAX_VALUE))))
    );
  }// </editor-fold>//GEN-END:initComponents
private ArrayList<ItemTransaksi> itemTransaksis = new ArrayList<>();
  private void txtPenjualanKodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenjualanKodeProdukActionPerformed
    // TODO add your handling code here:
    jButton1.doClick();
  }//GEN-LAST:event_txtPenjualanKodeProdukActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    addItem();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
    // TODO add your handling code here:        
  }//GEN-LAST:event_jTable1KeyPressed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    String kodeProduk = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    String namaProduk = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
    int dialogOptions = JOptionPane.YES_NO_OPTION;
    int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus item produk " + namaProduk + "?", "Hapus item", dialogOptions);
    if (dialogResult == JOptionPane.YES_OPTION) {
      int itemIndex = -1;
      int iterator1 = 0;
      for (ItemTransaksi item : itemTransaksis) {
        if (item.getKodeProduk().equals(kodeProduk)) {
          itemIndex = iterator1;
        }
        iterator1++;
      }
      itemTransaksis.remove(itemIndex);
      reloadItemData();
    }
    jButton4.setEnabled(false);
    jTable1.clearSelection();
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    // TODO add your handling code here:
    jButton4.setEnabled(true);
  }//GEN-LAST:event_jTable1MouseClicked

  private void cmbPenjualanBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPenjualanBuyerActionPerformed
    // TODO add your handling code here:
    int idUser = Integer.parseInt(cmbPenjualanBuyer.getItemAt(cmbPenjualanBuyer.getSelectedIndex()).getId());
    if (idUser > 1) {
      txtPenjualanBuyerNama.setText(null);
      txtPenjualanBuyerNama.setEnabled(false);
    } else {
      txtPenjualanBuyerNama.setEnabled(true);
    }
  }//GEN-LAST:event_cmbPenjualanBuyerActionPerformed
  private void addItem() {
    String kode = txtPenjualanKodeProduk.getText();
    Produk produk = Produk.getByKode(kode, 0);
    int itemIndex = -1;
    int iterator1 = 0;
    if (produk != null) {
      for (ItemTransaksi item : itemTransaksis) {
        if (item.getIdProduk() == produk.getId()) {
          itemIndex = iterator1;
        }
        iterator1++;
      }
      if (itemIndex > -1) {
        itemTransaksis.get(itemIndex).setJumlah(itemTransaksis.get(itemIndex).getJumlah() + 1);
//        System.out.println(itemTransaksis.get(itemIndex).getJumlah());
        itemTransaksis.get(itemIndex).setTotal(calcItemGrandTotal(itemTransaksis.get(itemIndex).getJumlah(), itemTransaksis.get(itemIndex).getHarga(), itemTransaksis.get(itemIndex).getDiskonItem()));
      } else {
        itemTransaksis.add(new ItemTransaksi(produk.getId(), produk.getKode(), produk.getNama(), 1, produk.getHarga(), produk.getHarga() * 1, 0, produk.getHarga() * 1));
      }
      txtPenjualanKodeProduk.setText(null);
      reloadItemData();
    } else {
      JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.", "Tambah item", 0);
    }
  }

  private double calcItemGrandTotal(double jumlah, double harga, double diskon) {
    return (jumlah * harga) - (jumlah * diskon);
  }

  private void reloadItemData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    for (ItemTransaksi item : itemTransaksis) {
      model.addRow(new Object[]{
        item.getKodeProduk(),
        item.getNamaProduk(),
        item.getHarga(),
        item.getJumlah(),
        item.getTotal()
      });
    }
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<CmbItem> cmbPenjualanBuyer;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField txtPenjualanBuyerNama;
  private javax.swing.JTextField txtPenjualanKodeProduk;
  // End of variables declaration//GEN-END:variables
}
