/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package xyz.galinfo.galipos.panels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import xyz.galinfo.galipos.models.Produk;

/**
 *
 * @author janud
 */
public class PanelProduk extends javax.swing.JPanel {

  private Produk currentProduk;

  /**
   * Creates new form PanelDashboard
   */
  public PanelProduk() {
    initComponents();
    loadDataProduk(null, null);
  }

  private void loadDataProduk(String columnName, String qWord) {
    ArrayList<Produk> produks = Produk.getAll(columnName, qWord);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    for (Produk produk : produks) {
      model.addRow(new Object[]{
        produk.getKode(),
        produk.getNama(),
        produk.getHarga(),
        produk.getStok(),
        produk.getSatuan(),
        produk.getStokKritis(),
        produk.getStatus().equals("aktif") ? "YA" : "TIDAK"
      });
    }
    jLabel6.setText(model.getRowCount() + "");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtProdukKode = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtProdukNama = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtProdukSatuan = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    txtProdukHarga = new javax.swing.JFormattedTextField();
    jLabel9 = new javax.swing.JLabel();
    txtProdukStok = new javax.swing.JFormattedTextField();
    jLabel10 = new javax.swing.JLabel();
    txtProdukStokKritis = new javax.swing.JFormattedTextField();
    jLabel11 = new javax.swing.JLabel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    txtProdukKeyword = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    jPanel1.setBackground(new java.awt.Color(0, 102, 153));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("PRODUK");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setText("Kode");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));
    jPanel2.add(txtProdukKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

    jLabel3.setText("Nama");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
    jPanel2.add(txtProdukNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, -1));

    jLabel7.setText("Satuan");
    jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
    jPanel2.add(txtProdukSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, -1));

    jLabel8.setText("Harga");
    jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

    txtProdukHarga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    txtProdukHarga.setText("0");
    jPanel2.add(txtProdukHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 240, -1));

    jLabel9.setText("Stok");
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

    txtProdukStok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    txtProdukStok.setText("0");
    jPanel2.add(txtProdukStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, -1));

    jLabel10.setText("Stok kritis");
    jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

    txtProdukStokKritis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
    txtProdukStokKritis.setText("0");
    jPanel2.add(txtProdukStokKritis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, -1));

    jLabel11.setText("Status");
    jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("Tidak dijual");
    jRadioButton1.setActionCommand("nonaktif");
    jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setSelected(true);
    jRadioButton2.setText("Dijual");
    jRadioButton2.setActionCommand("aktif");
    jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

    jButton2.setText("Batal");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

    jButton3.setText("Simpan");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

    jButton4.setText("Hapus");
    jButton4.setEnabled(false);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

    txtProdukKeyword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtProdukKeywordActionPerformed(evt);
      }
    });

    jButton1.setText("Reset");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel4.setText("produk");

    jLabel5.setText("Total:");

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel6.setText("0");

    jTable1.setAutoCreateRowSorter(true);
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Kode", "Nama", "Harga", "Stok", "Satuan", "Stok kritis", "Dijual"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(txtProdukKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(386, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtProdukKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel5)
          .addComponent(jLabel6))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    actionForm();
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    resetForm();
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    // TODO add your handling code here:
    String kode = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    Produk produk = Produk.getByKode(kode, 0);
    if (produk != null) {
      currentProduk = produk;
      txtProdukKode.setText(currentProduk.getKode());
      txtProdukNama.setText(currentProduk.getNama());
      txtProdukSatuan.setText(currentProduk.getSatuan());
      txtProdukHarga.setText(currentProduk.getHarga() + "");
      txtProdukStok.setText(currentProduk.getStok() + "");
      txtProdukStokKritis.setText(currentProduk.getStokKritis() + "");
      if (currentProduk.getStatus().equals("aktif")) {
        jRadioButton2.setSelected(true);
      } else {
        jRadioButton1.setSelected(true);
      }
      jButton4.setEnabled(true);
    } else {
      JOptionPane.showMessageDialog(this, "Data tidak ditemukan.", "Input error", 0);
    }
  }//GEN-LAST:event_jTable1MouseClicked

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    int dialogOptions = JOptionPane.YES_NO_OPTION;
    int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus produk dengan nama " + currentProduk.getNama() + "?", "Hapus produk", dialogOptions);
    if (dialogResult == JOptionPane.YES_OPTION) {
      if (currentProduk.delete() != null) {
        JOptionPane.showMessageDialog(this, "Produk dengan nama " + currentProduk.getNama() + " berhasil dihapus.", "Hapus produk", 1);
        currentProduk = null;
        resetForm();
        loadDataProduk(null, null);
      } else {
        JOptionPane.showMessageDialog(this, "Produk dengan nama " + currentProduk.getNama() + " gagal dihapus.", "Hapus produk", 0);
      }
    }
  }//GEN-LAST:event_jButton4ActionPerformed

  private void txtProdukKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdukKeywordActionPerformed
    // TODO add your handling code here:
    String qWord = txtProdukKeyword.getText();
    resetForm();
    currentProduk = null;
    loadDataProduk("combined", qWord);
  }//GEN-LAST:event_txtProdukKeywordActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    txtProdukKeyword.setText(null);
    resetForm();
    loadDataProduk(null, null);
  }//GEN-LAST:event_jButton1ActionPerformed
  private void resetForm() {
    currentProduk = null;
    jButton4.setEnabled(false);
    txtProdukKode.setText(null);
    txtProdukNama.setText(null);
    txtProdukSatuan.setText(null);
    txtProdukHarga.setText("0");
    txtProdukStok.setText("0");
    txtProdukStokKritis.setText("0");
    jRadioButton2.setSelected(true);
  }

  private void actionForm() {
    String kode = txtProdukKode.getText();
    String nama = txtProdukNama.getText();
    String satuan = txtProdukSatuan.getText();
    String hargaText = txtProdukHarga.getText();
    String stokText = txtProdukStok.getText();
    String stokKritisText = txtProdukStokKritis.getText();
    String status = buttonGroup1.getSelection().getActionCommand();
    Double harga = 0.0, stok = 0.0, stokKritis = 0.0;
    boolean isValid = true;
    if (kode.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Kode harus diisi.", "Tambah produk", 0);
    } else if (Produk.getByKode(kode, currentProduk != null ? currentProduk.getId() : 0) != null) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Kode tersebut sudah digunakan.", "Tambah produk", 0);
    } else if (nama.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Nama harus diisi.", "Tambah produk", 0);
    } else if (Produk.getByNama(nama, currentProduk != null ? currentProduk.getId() : 0) != null) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Nama tersebut sudah digunakan.", "Tambah produk", 0);
    } else if (satuan.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Satuan harus diisi.", "Tambah produk", 0);
    } else if (hargaText.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Harga harus diisi.", "Tambah produk", 0);
    } else if (stokText.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Stok harus diisi.", "Tambah produk", 0);
    } else if (stokKritisText.length() == 0) {
      isValid = false;
      JOptionPane.showMessageDialog(this, "Stok kritis harus diisi.", "Tambah produk", 0);
    } else {
      harga = Double.valueOf(hargaText);
      stok = Double.valueOf(stokText);
      stokKritis = Double.valueOf(stokKritisText);
    }
    if (isValid) {
      Produk produk;
      String word1 = "Tambah";
      if (currentProduk == null) {
        produk = new Produk();
      } else {
        produk = currentProduk;
        word1 = "Simpan";
      }
      produk.setKode(kode);
      produk.setNama(nama);
      produk.setSatuan(satuan);
      produk.setHarga(harga);
      produk.setStok(stok);
      produk.setStokKritis(stokKritis);
      produk.setStatus(status);
      if (produk.save() != null) {
        JOptionPane.showMessageDialog(this, "Produk " + nama + " berhasil disimpan.", word1 + " produk", 1);
        resetForm();
        loadDataProduk(null, null);
      } else {
        JOptionPane.showMessageDialog(this, "Produk " + nama + " gagal disimpan.", word1 + " produk", 0);
      }
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JFormattedTextField txtProdukHarga;
  private javax.swing.JTextField txtProdukKeyword;
  private javax.swing.JTextField txtProdukKode;
  private javax.swing.JTextField txtProdukNama;
  private javax.swing.JTextField txtProdukSatuan;
  private javax.swing.JFormattedTextField txtProdukStok;
  private javax.swing.JFormattedTextField txtProdukStokKritis;
  // End of variables declaration//GEN-END:variables
}
